# Generated by Django 2.1.4 on 2019-01-14 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actstream', '0005_auto_20190114_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='type',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'INSURELYNK_LOG'), (2, 'PATIENTLYNK_LOG'), (3, 'PROVIDERLYNK_LOG')], null=True),
        ),
    ]
