# Generated by Django 2.1.7 on 2019-06-29 14:10

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('actstream', '0006_action_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='data',
            field=django_mysql.models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
