# Generated by Django 2.1.7 on 2019-06-29 14:10

from django.db import migrations

try:
    import django_mysql.models
    JSONFieldClass = django_mysql.models.JSONField
except (ImportError, AttributeError):
    # Django 3.1+ has native JSONField
    from django.db.models import JSONField as JSONFieldClass


class Migration(migrations.Migration):

    dependencies = [
        ('actstream', '0006_action_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='data',
            field=JSONFieldClass(blank=True, default=dict, null=True),
        ),
    ]
