# Generated by Django 3.2 on 2024-01-25 15:53

import actstream.apps
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actstream', '0008_auto_20191107_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='data',
            field=models.JSONField(blank=True, encoder=actstream.apps.CustomEncoder, null=True),
        ),
    ]
